### ISSUE TITLE
Original dates for observed days 

### ISSUE THREAD

**Issue by jbroudou** [CharlieHR/national-holidays-config#58]
When an observed day (i.e. holidays that are moved because they are on a weekend) is returned would it possible to return the original date as well? 

Also, in some locations when a holiday falls on a weekend, it is moved to a weekday as an observed day. In some of these locations only the observed day is considered a holiday whereas in others both the observed and original days are considered holidays. This is an important distinction in some jurisdictions. 

Is there any chance of supporting an addition flag against observed holidays that indiate the original day is or isn't a holiday?

**Comment by kaoru** [comment]
hi @jbroudou,

This is certainly an interesting idea! I think it's something we could probably add to the spec.

We already have the currently unused `public_holiday: true` on every holiday. My original intention with that was that we could have other significant dates, like Saints days which aren't public holidays, but so far we've not included any of them (because they're not actually that relevant to our particular use case.)

So one way we could handle your suggestion would by be using that... we could have:

```
  - public_holiday: false
    date: '2017-01-01'
    names:
      en: New Year's Day
  - public_holiday: true
    date: '2017-01-02'
    names:
      en: New Year's Day (observed)
```

Without adding anything to the spec.

Alternatively, if you wanted them to actually be linked, I think it would be something like:

```
  - public_holiday: true
    date: '2017-01-01'
    observed_date: '2017-01-02'
    names:
      en: New Year's Day
```

Maybe?

What's your use case?

**Comment by jbroudou** [comment]
Hi @kaoru  Although it would require changing the spec, I think the link method is explicit and would be less prone to errors especially when you factor in non English translations. 

```yaml
- public_holiday: true
    date: '2017-01-01'
    observed_date: '2017-01-02'
    names:
      en: New Year's Day
```

regarding the second part of my question, as an example see

https://www.industrialrelations.nsw.gov.au/public-holidays/public-holidays-in-nsw/

> 2 The public holiday standard in the Public Holidays Act 2010 provides that when Australia Day (26 January) falls on a Saturday or Sunday, there will be no public holiday on that day and instead the following Monday is to be the public holiday.

> 3 The public holiday standard in the Act provides that when New Year's Day, Christmas Day or Boxing Day falls on a Saturday or Sunday there is to be an additional public holiday on the following Monday or Tuesday.

It seems like **public_holiday** could be used to identify if the original date is a holiday.
